# Generated by Django 5.1.4 on 2025-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_des_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='des',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='posts_Images/'),
        ),
    ]
